import { initializeApp, FirebaseApp } from 'firebase/app';
import { getDatabase, Database } from 'firebase/database';
import { initializeAuth, getReactNativePersistence, getAuth, Auth, signInWithCustomToken } from 'firebase/auth';
import ReactNativeAsyncStorage from '@react-native-async-storage/async-storage';
import Constants from 'expo-constants';

// Firebase Web App Configuration from environment variables
// Note: These are public credentials for client-side Firebase SDK
// Security is enforced through Firebase Security Rules, not credential secrecy
const firebaseConfig = {
  apiKey: Constants.expoConfig?.extra?.firebase?.apiKey || '',
  authDomain: Constants.expoConfig?.extra?.firebase?.authDomain || '',
  databaseURL: Constants.expoConfig?.extra?.firebase?.databaseURL || '',
  projectId: Constants.expoConfig?.extra?.firebase?.projectId || '',
  storageBucket: Constants.expoConfig?.extra?.firebase?.storageBucket || '',
  messagingSenderId: Constants.expoConfig?.extra?.firebase?.messagingSenderId || '',
  appId: Constants.expoConfig?.extra?.firebase?.appId || '',
  measurementId: Constants.expoConfig?.extra?.firebase?.measurementId || '',
};

// Validate Firebase configuration (warn instead of crashing the app)
const firebaseConfigValid = !!(firebaseConfig.apiKey && firebaseConfig.databaseURL && firebaseConfig.projectId);
if (!firebaseConfigValid) {
  console.warn('[Firebase] Configuration missing or incomplete - Firebase features will be disabled.');
  console.warn('[Firebase] apiKey:', firebaseConfig.apiKey ? 'set' : 'MISSING');
  console.warn('[Firebase] databaseURL:', firebaseConfig.databaseURL ? 'set' : 'MISSING');
  console.warn('[Firebase] projectId:', firebaseConfig.projectId ? 'set' : 'MISSING');
}

let app: FirebaseApp | null = null;
let database: Database | null = null;
let auth: Auth | null = null;

/**
 * Initialize Firebase app, database, and auth
 * Safe to call multiple times - returns existing instances
 */
export const initializeFirebase = () => {
  if (!firebaseConfigValid) {
    console.warn('[Firebase] Cannot initialize - configuration is missing');
    return { app: null, database: null, auth: null };
  }

  if (app && database && auth) {
    console.log('[Firebase] Already initialized, returning existing instances');
    return { app, database, auth };
  }

  try {
    if (!app) {
      app = initializeApp(firebaseConfig);
    }
    if (!database) {
      database = getDatabase(app);
    }
    if (!auth) {
      try {
        auth = initializeAuth(app, {
          persistence: getReactNativePersistence(ReactNativeAsyncStorage),
        });
      } catch (authError: any) {
        // Fallback: initializeAuth fails with "Component auth has not been registered yet"
        // when @react-native-firebase/app conflicts with firebase web SDK,
        // or when auth was already initialized. getAuth returns the existing instance.
        console.warn('[Firebase] initializeAuth failed, using getAuth fallback:', authError.message);
        auth = getAuth(app);
      }
    }

    console.log('[Firebase] Initialized successfully');
    console.log('[Firebase] Database URL:', firebaseConfig.databaseURL);

    return { app, database, auth };
  } catch (error) {
    console.error('[Firebase] Initialization failed:', error);
    throw error;
  }
};

/**
 * Get Firebase Database instance
 * Initializes Firebase if not already initialized
 */
export const getFirebaseDatabase = (): Database => {
  if (!firebaseConfigValid) {
    throw new Error('[Firebase] Cannot get database - configuration is missing');
  }
  if (!database) {
    console.log('[Firebase] Database not initialized, initializing now...');
    initializeFirebase();
  }
  return database!;
};

/**
 * Get Firebase Auth instance
 * Initializes Firebase if not already initialized
 */
export const getFirebaseAuth = (): Auth => {
  if (!firebaseConfigValid) {
    throw new Error('[Firebase] Cannot get auth - configuration is missing');
  }
  if (!auth) {
    console.log('[Firebase] Auth not initialized, initializing now...');
    initializeFirebase();
  }
  return auth!;
};

/**
 * Authenticate with Firebase using custom token from backend
 * @param customToken - Custom token generated by backend
 */
export const authenticateFirebase = async (customToken: string): Promise<void> => {
  try {
    const authInstance = getFirebaseAuth();
    const userCredential = await signInWithCustomToken(authInstance, customToken);

    console.log('[Firebase] Authenticated successfully');
    console.log('[Firebase] User ID:', userCredential.user.uid);
  } catch (error) {
    console.error('[Firebase] Authentication failed:', error);
    throw error;
  }
};

/**
 * Sign out from Firebase
 */
export const signOutFirebase = async (): Promise<void> => {
  try {
    const authInstance = getFirebaseAuth();
    await authInstance.signOut();
    console.log('[Firebase] Signed out successfully');
  } catch (error) {
    console.error('[Firebase] Sign out failed:', error);
    throw error;
  }
};
